name: powerstat
version: git
version-script: |
    echo $(git describe --tags)
summary: computer power measuring tool
description: Powerstat measures the power consumption of a computer that has a battery power source or an Intel RAPL power domain.  The output is like vmstat but also shows power consumption statistics.  At the end of a run, powerstat will calculate the average, standard deviation and min/max of the gathered data.
confinement: strict
type: app
grade: stable

parts:
    powerstat:
        plugin: make
        source: git://kernel.ubuntu.com/cking/powerstat
        build-packages:
            - gcc
            - make

apps:
    powerstat:
        command: usr/bin/powerstat
        plugs: [hardware-observe,netlink-connector,system-observe]

